instructors = [
	"Aaron Elmore",
	"Aaron Potechin",
	"Adam Shaw",
	"Alex Kale",
	"Alexander Razborov",
	"Aloni Cohen",
	"Anne Rogers",
	"Ari Holtzman",
	"Ben Zhao",
	"Blase Ur",
	"Borja Sotomayor",
	"Chenhao Tan",
	"David Cash",
	"Frederic Chong",
	"Gordon Kindlmann",
	"Grant Ho",
	"Haifeng Xu",
	"Hannah Morgan",
	"Haotian Jiang",
	"Haryadi Gunawi",
	"Heather Zheng",
	"Janos Simon",
	"John Reppy",
	"Junchen Jiang",
	"Ken Nakagaki",
	"Kexin Pei",
	"Laszlo Babai",
	"Lorenzo Orecchia",
	"Marshini Chetty",
	"Matthew Wachs",
	"Michael Maire",
	"Mina Lee",
	"Mohammed Suhail Rehman",
	"Nick Feamster",
	"Pedro Lopes",
	"Rana Hanocka",
	"Raul Castro Fernandez",
	"Ravi Chugh",
	"Rebecca Willett",
	"Risi Kondor",
	"Robert Rand",
	"Sarah Sebo",
	"Tian Li",
	"Timothy Ng",
	"William Fefferman",
	"William Hoza",
	"Yali Amit",
	"Yanjing Li",
	"Yuxin Chen",
];


instructors_with_ids = [{"label": name, "id": idx + 1} for idx, name in enumerate(instructors)]

for instructor in instructors_with_ids:
    print(instructor)