import * as React from "react";
export const majors = [
	{ label: "All - Subjects", id: 1 },
	{ label: "AANL - Ancient Anatolian Languages", id: 2 },
	{ label: "AASR - Anthro/Sociology of Religion", id: 3 },
	{ label: "ADSP - Applied Data Science", id: 4 },
	{ label: "AKKD - Akkadian", id: 5 },
	{ label: "AMER - American Culture", id: 6 },
	{ label: "ANCM - Ancient Mediterranean World", id: 7 },
	{ label: "ANTH - Anthropology", id: 8 },
	{ label: "ARAB - Arabic", id: 9 },
	{ label: "ARAM - Aramaic", id: 10 },
	{ label: "ARCH - Architectural Studies", id: 11 },
	{ label: "ARME - Armenian", id: 12 },
	{ label: "ARTH - Art History", id: 13 },
	{ label: "ARTV - Visual Arts", id: 14 },
	{ label: "ASLG - American Sign Language", id: 15 },
	{ label: "ASTR - Astronomy/Astrophysics", id: 16 },
	{ label: "BANG - Bangla", id: 17 },
	{ label: "BASQ - Basque", id: 18 },
	{ label: "BBIO - Business of Biotechnology", id: 19 },
	{ label: "BCMB - Biochemistry/Molecular Biology", id: 20 },
	{ label: "BCSN - Bosnian/Croatian/Serbian", id: 21 },
	{ label: "BIBL - Biblical Studies", id: 22 },
	{ label: "BIOS - Biological Sciences (College)", id: 23 },
	{ label: "BMSC - Biomedical Sciences", id: 24 },
	{ label: "BPHS - Biophysical Sciences", id: 25 },
	{ label: "BPRO - Big Problems", id: 26 },
	{ label: "BSDG - Biological Sciences (Graduate)", id: 27 },
	{ label: "BSSR - BSCD Summer Research", id: 28 },
	{ label: "BULG - Bulgarian", id: 29 },
	{ label: "BUSF - Business - Full-Time MBA/PhD", id: 30 },
	{ label: "BUSN - Business", id: 31 },
	{ label: "BUSV - Business - Summer Scholars", id: 32 },
	{ label: "CAAM - Computational and Applied Math", id: 33 },
	{ label: "CABI - Cancer Biology", id: 34 },
	{ label: "CAPP - Comp Analysis/Public Pol", id: 35 },
	{ label: "CATA - Catalan", id: 36 },
	{ label: "CCCT - Center for Contemporary Theory", id: 37 },
	{ label: "CCTS - Clinical/Translational Science", id: 38 },
	{ label: "CDIN - Disciplinary Innovation", id: 39 },
	{ label: "CEGU - Environment/Geog/Urbanization", id: 40 },
	{ label: "CHDV - Comparative Human Development", id: 41 },
	{ label: "CHEM - Chemistry", id: 42 },
	{ label: "CHIN - Chinese", id: 43 },
	{ label: "CHSS - Conceptual/Hist Studies of Sci", id: 44 },
	{ label: "CHST - Chicago Studies", id: 45 },
	{ label: "CLAS - Classics", id: 46 },
	{ label: "CLCV - Classical Civilization", id: 47 },
	{ label: "CMES - Middle Eastern Studies", id: 48 },
	{ label: "CMLT - Comparative Literature", id: 49 },
	{ label: "CMSC - Computer Science", id: 50 },
	{ label: "CMST - Cinema/Media Studies", id: 51 },
	{ label: "COGS - Cognitive Science", id: 52 },
	{ label: "CPNS - Computational Neuroscience", id: 53 },
	{ label: "CPPE - Pathway Program in Economics", id: 54 },
	{ label: "CRES - Comp Race/Ethnic Studies", id: 55 },
	{ label: "CRSH - CIC CourseShare", id: 56 },
	{ label: "CRWR - Creative Writing", id: 57 },
	{ label: "CTMI - Clinical Trials Management", id: 58 },
	{ label: "CZEC - Czech", id: 59 },
	{ label: "DATA - Data Science", id: 60 },
	{ label: "DEMS - Democracy Studies", id: 61 },
	{ label: "DIGS - Digital Humanities", id: 62 },
	{ label: "DVBI - Developmental Biology", id: 63 },
	{ label: "DVPR - Philosophy of Religions", id: 64 },
	{ label: "DVSR - Psych/Sociology of Religion", id: 65 },
	{ label: "EALC - East Asian Languages/Civ", id: 66 },
	{ label: "ECEV - Ecology/Evolution", id: 67 },
	{ label: "ECMA - Economics (ECMA)", id: 68 },
	{ label: "ECON - Economics", id: 69 },
	{ label: "EDSO - Education and Society", id: 70 },
	{ label: "EEUR - East European", id: 71 },
	{ label: "EGPT - Egyptian", id: 72 },
	{ label: "ELIN - English Language Institute", id: 73 },
	{ label: "ENGL - English Language/Literature", id: 74 },
	{ label: "ENSC - Environmental Sciences", id: 75 },
	{ label: "ENST - Environmental/Urban Studies", id: 76 },
	{ label: "ESLG - English Language Institute", id: 77 },
	{ label: "EVOL - Evolutionary Biology", id: 78 },
	{ label: "FINM - Financial Mathematics", id: 79 },
	{ label: "FNDL - Fundamentals: Issues/Texts", id: 80 },
	{ label: "FREN - French", id: 81 },
	{ label: "GEEZ - Ge'ez", id: 82 },
	{ label: "GENE - Genetics", id: 83 },
	{ label: "GEOG - Geographical Sciences", id: 84 },
	{ label: "GEOR - Georgian", id: 85 },
	{ label: "GEOS - Geophysical Sciences", id: 86 },
	{ label: "GISC - Geographic Information Science", id: 87 },
	{ label: "GLST - Global Studies", id: 88 },
	{ label: "GNSE - Gender/Sexuality Studies", id: 89 },
	{ label: "GREK - Greek", id: 90 },
	{ label: "GRMN - German", id: 91 },
	{ label: "HCHR - History of Christianity", id: 92 },
	{ label: "HCUL - History of Culture", id: 93 },
	{ label: "HEBR - Hebrew", id: 94 },
	{ label: "HGEN - Human Genetics", id: 95 },
	{ label: "HIJD - History of Judaism", id: 96 },
	{ label: "HIND - Hindi", id: 97 },
	{ label: "HIPS - HIPS", id: 98 },
	{ label: "HIST - History", id: 99 },
	{ label: "HLTH - Health and Society", id: 100 },
	{ label: "HMRT - Human Rights", id: 101 },
	{ label: "HNUT - Hum Nutrition/Nutritional Bio", id: 102 },
	{ label: "HREL - History of Religions", id: 103 },
	{ label: "HSTD - Health Studies", id: 104 },
	{ label: "HUMA - Humanities", id: 105 },
	{ label: "IMMU - Immunology", id: 106 },
	{ label: "INRE - International Relations", id: 107 },
	{ label: "INST - International Studies", id: 108 },
	{ label: "IRHU - Inquiry/Research in Humanities", id: 109 },
	{ label: "ISHU - Humanities Interdisc Studies", id: 110 },
	{ label: "ISLM - Islamic Studies", id: 111 },
	{ label: "ITAL - Italian", id: 112 },
	{ label: "JAPN - Japanese", id: 113 },
	{ label: "JWSC - Jewish Studies", id: 114 },
	{ label: "JWSG - Committee on Jewish Studies", id: 115 },
	{ label: "KAZK - Kazak", id: 116 },
	{ label: "KNOW - KNOW", id: 117 },
	{ label: "KORE - Korean", id: 118 },
	{ label: "KREY - Haitian Kreyol", id: 119 },
	{ label: "LACS - Latin Amer/Caribbean Studies", id: 120 },
	{ label: "LATN - Latin", id: 121 },
	{ label: "LAWS - Laws", id: 122 },
	{ label: "LGLN - Languages in Linguistics", id: 123 },
	{ label: "LING - Linguistics", id: 124 },
	{ label: "LLSO - Law/Letters/Society", id: 125 },
	{ label: "MAAD - Media Arts and Design", id: 126 },
	{ label: "MACS - Computational Social Science", id: 127 },
	{ label: "MAPH - MAPH (MA in Humanities)", id: 128 },
	{ label: "MAPS - MAPSS (MA in Social Sciences)", id: 129 },
	{ label: "MARA - Marathi", id: 130 },
	{ label: "MATH - Mathematics", id: 131 },
	{ label: "MDVL - Medieval Studies", id: 132 },
	{ label: "MEDC - Medicine", id: 133 },
	{ label: "MENG - Molecular Engineering", id: 134 },
	{ label: "MGCB - Molecular Genetics/Cell Bio", id: 135 },
	{ label: "MICR - Microbiology", id: 136 },
	{ label: "MLAP - Master of Liberal Arts", id: 137 },
	{ label: "MOGK - Modern Greek", id: 138 },
	{ label: "MOLM - Molecular Medicine", id: 139 },
	{ label: "MOMN - Molecular Metabolism/Nutrition", id: 140 },
	{ label: "MPCS - Computer Science Masters", id: 141 },
	{ label: "MPHY - Medical Physics", id: 142 },
	{ label: "MPMM - Molecular Pathogenesis/Med", id: 143 },
	{ label: "MSBI - M.S. in Biomedical Informatics", id: 144 },
	{ label: "MSCA - M.S. in Analytics", id: 145 },
	{ label: "MSPH - Precision Health", id: 146 },
	{ label: "MSTR - M.S. in Threat/Response Mgmt", id: 147 },
	{ label: "MUSI - Music", id: 148 },
	{ label: "NCDV - New Collegiate Division", id: 149 },
	{ label: "NEAA - Near Eastern Art/Archeology", id: 150 },
	{ label: "NEHC - Near Eastern History/Civ", id: 151 },
	{ label: "NELC - Near Eastern Languages/Civ", id: 152 },
	{ label: "NELG - Near Eastern Languages", id: 153 },
	{ label: "NORW - Norwegian", id: 154 },
	{ label: "NPHP - Neuro/Pharma/Physio", id: 155 },
	{ label: "NSCI - Neuroscience", id: 156 },
	{ label: "NSFP - NSF - Physics", id: 157 },
	{ label: "NTEC - New Testament/ECL", id: 158 },
	{ label: "NTSC - Natural Science", id: 159 },
	{ label: "NURB - Neurobiology", id: 160 },
	{ label: "ORGB - Organismal Biology/Anatomy", id: 161 },
	{ label: "PALI - Pali", id: 162 },
	{ label: "PARR - Parrhesia Public Discourse", id: 163 },
	{ label: "PATH - Pathology", id: 164 },
	{ label: "PBHS - Public Health Sciences", id: 165 },
	{ label: "PBPL - Public Policy Studies (PBPL)", id: 166 },
	{ label: "PECO - Political Economy", id: 167 },
	{ label: "PERS - Persian", id: 168 },
	{ label: "PHIL - Philosophy", id: 169 },
	{ label: "PHSC - Physical Science", id: 170 },
	{ label: "PHYS - Physics", id: 171 },
	{ label: "PLSC - Political Science", id: 172 },
	{ label: "POLI - Polish", id: 173 },
	{ label: "PORT - Portuguese", id: 174 },
	{ label: "PPHA - Public Policy Studies (PPHA)", id: 175 },
	{ label: "PSMS - Physical Sciences Masters", id: 176 },
	{ label: "PSYC - Psychology", id: 177 },
	{ label: "PWAY - Pathway Program", id: 178 },
	{ label: "RAME - Religions in America", id: 179 },
	{ label: "RDIN - Race, Diaspora,and Indigeneity", id: 180 },
	{ label: "REES - Russian/East European Studies", id: 181 },
	{ label: "RELP - Religious Leadership/Practice", id: 182 },
	{ label: "REMS - Ren/Early Modern Studies", id: 183 },
	{ label: "RETH - Religious Ethics", id: 184 },
	{ label: "RLIT - Religion/Literature", id: 185 },
	{ label: "RLLT - Romance Languages/Literature", id: 186 },
	{ label: "RLST - Religious Studies", id: 187 },
	{ label: "RLVC - Religion/Lit/Visual Culture", id: 188 },
	{ label: "RUSS - Russian", id: 189 },
	{ label: "SABR - Study Abroad", id: 190 },
	{ label: "SALC - South Asian Languages/Civ", id: 191 },
	{ label: "SANS - Sanskrit", id: 192 },
	{ label: "SCPD - Science Comm/Public Discourse", id: 193 },
	{ label: "SCTH - Social Thought", id: 194 },
	{ label: "SIGN - Signature Courses", id: 195 },
	{ label: "SLAV - General Slavic", id: 196 },
	{ label: "SMSP - Summer Special Programs", id: 197 },
	{ label: "SOCI - Sociology", id: 198 },
	{ label: "SOSC - Social Sciences", id: 199 },
	{ label: "SOSL - South Slavic", id: 200 },
	{ label: "SPAN - Spanish", id: 201 },
	{ label: "SSAD - Social Service Administration", id: 202 },
	{ label: "STAT - Statistics", id: 203 },
	{ label: "SUAS - Summer Arts & Sciences", id: 204 },
	{ label: "SUMR - Sumerian", id: 205 },
	{ label: "SWAH - Swahili", id: 206 },
	{ label: "TAML - Tamil", id: 207 },
	{ label: "TAPS - Theater/Performance Studies", id: 208 },
	{ label: "TBTN - Tibetan", id: 209 },
	{ label: "THEO - Theology", id: 210 },
	{ label: "TLGU - Telegu", id: 211 },
	{ label: "TTIC - Toyota Tech Inst at Chicago", id: 212 },
	{ label: "TURK - Turkish", id: 213 },
	{ label: "UGAR - Ugaritic", id: 214 },
	{ label: "URDU - Urdu", id: 215 },
	{ label: "UTEP - Urban Teacher Education", id: 216 },
	{ label: "UZBK - Uzbek", id: 217 },
	{ label: "WOLO - Wolof", id: 218 },
	{ label: "YDDH - Yiddish", id: 219 },
];

export const instructors = [
	{ label: "Aaron Elmore", id: 1 },
	{ label: "Aaron Potechin", id: 2 },
	{ label: "Adam Shaw", id: 3 },
	{ label: "Alex Kale", id: 4 },
	{ label: "Alexander Razborov", id: 5 },
	{ label: "Aloni Cohen", id: 6 },
	{ label: "Anne Rogers", id: 7 },
	{ label: "Ari Holtzman", id: 8 },
	{ label: "Ben Zhao", id: 9 },
	{ label: "Blase Ur", id: 10 },
	{ label: "Borja Sotomayor", id: 11 },
	{ label: "Chenhao Tan", id: 12 },
	{ label: "David Cash", id: 13 },
	{ label: "Frederic Chong", id: 14 },
	{ label: "Gordon Kindlmann", id: 15 },
	{ label: "Grant Ho", id: 16 },
	{ label: "Haifeng Xu", id: 17 },
	{ label: "Hannah Morgan", id: 18 },
	{ label: "Haotian Jiang", id: 19 },
	{ label: "Haryadi Gunawi", id: 20 },
	{ label: "Heather Zheng", id: 21 },
	{ label: "Janos Simon", id: 22 },
	{ label: "John Reppy", id: 23 },
	{ label: "Junchen Jiang", id: 24 },
	{ label: "Ken Nakagaki", id: 25 },
	{ label: "Kexin Pei", id: 26 },
	{ label: "Laszlo Babai", id: 27 },
	{ label: "Lorenzo Orecchia", id: 28 },
	{ label: "Marshini Chetty", id: 29 },
	{ label: "Matthew Wachs", id: 30 },
	{ label: "Michael Maire", id: 31 },
	{ label: "Mina Lee", id: 32 },
	{ label: "Mohammed Suhail Rehman", id: 33 },
	{ label: "Nick Feamster", id: 34 },
	{ label: "Pedro Lopes", id: 35 },
	{ label: "Rana Hanocka", id: 36 },
	{ label: "Raul Castro Fernandez", id: 37 },
	{ label: "Ravi Chugh", id: 38 },
	{ label: "Rebecca Willett", id: 39 },
	{ label: "Risi Kondor", id: 40 },
	{ label: "Robert Rand", id: 41 },
	{ label: "Sarah Sebo", id: 42 },
	{ label: "Tian Li", id: 43 },
	{ label: "Timothy Ng", id: 44 },
	{ label: "William Fefferman", id: 45 },
	{ label: "William Hoza", id: 46 },
	{ label: "Yali Amit", id: 47 },
	{ label: "Yanjing Li", id: 48 },
	{ label: "Yuxin Chen", id: 49 },
];
